version: "3.9"

volumes:
  php-fpm-socket:
  db-store:

services:
  nginx:
    container_name: mememo-nginx
    build:
      context: ./
      dockerfile: ./infra/docker/development/nginx/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./infra/docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - laravel
      - nextjs

  laravel:
    container_name: mememo-laravel
    build:
      context: ./
      dockerfile: ./infra/docker/development/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./laravel:/work/laravel

  nextjs:
    container_name: mememo-nextjs
    build:
      context: ./
      dockerfile: ./infra/docker/development/nextjs/Dockerfile
    volumes:
      - ./nextjs:/work/nextjs
    ports:
      - 3000:3000

  db:
    container_name: mememo-db
    build:
      context: ./
      dockerfile: ./infra/docker/development/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 43306:3306 # 外部からDB内へのアクセス用
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
