version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: ./infra/development/nginx/Dockerfile
    volumes:
      - ./infra/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: ./infra/development/php/Dockerfile
    volumes:
      - ./laravel:/var/www/html

  db:
    build:
      context: ./
      dockerfile: ./infra/development/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
