version: "3.9"

volumes:
  php-fpm-socket:
  db-store:


services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./infra/docker/development/nginx/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./laravel:/work/laravel
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./infra/docker/development/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./laravel:/work/laravel

  db:
    container_name: db
    build:
      context: ./
      dockerfile: ./infra/docker/development/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 43306:3306 # 外部からDB内へのアクセス用
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  vite:
    container_name: vite
    build:
      context: ./
      dockerfile: ./infra/docker/development/vite/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./laravel:/work/laravel
